// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt sql.NullTime
}
